import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask
import java.io.File
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
}

group = "co.branch"
version = "0.1.0-SNAPSHOT"

/**
 * Embeds every JSON fixture file under fixtures/ as base64 into a single generated Kotlin file,
 * so the migration's correctness-contract fixtures are readable from commonTest on every KMP
 * target, including wasmJs and iOS, which have no test-resources filesystem to read from at
 * runtime.
 *
 * Each fixture's base64 is split into chunks well under the JVM class-file 65,535-byte UTF-8
 * constant limit, so no single string literal in the generated file approaches it.
 */
abstract class GenerateFixturesTask : DefaultTask() {

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val fixtureFiles: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @OptIn(ExperimentalEncodingApi::class)
    @TaskAction
    fun generate() {
        val chunkSize = 16_000

        val jsonFiles: List<File> = fixtureFiles.files
            .filter { it.isFile && it.extension == "json" }
            .sortedBy { it.name } // deterministic output

        require(jsonFiles.isNotEmpty()) {
            "No fixture files found. Expected JSON files under fixtures/."
        }

        val entries: List<String> = jsonFiles.map { file ->
            val base64: String = Base64.encode(file.readBytes())
            val chunkLiterals: String = base64
                .chunked(chunkSize)
                .joinToString(separator = ",\n") { chunk -> "        \"$chunk\"" }

            """
            |    "${file.name}" to decodeBase64(
            |        listOf(
            |$chunkLiterals,
            |        ).joinToString(""),
            |    ),
            """.trimMargin()
        }

        val source = buildString {
            appendLine("// GENERATED by the generateFixtures Gradle task. Do not edit.")
            appendLine("package co.branch.jsonlogic.fixtures")
            appendLine()
            appendLine("import kotlin.io.encoding.Base64")
            appendLine("import kotlin.io.encoding.ExperimentalEncodingApi")
            appendLine()
            appendLine("@OptIn(ExperimentalEncodingApi::class)")
            appendLine("private fun decodeBase64(base64: String): String = Base64.decode(base64).decodeToString()")
            appendLine()
            appendLine("internal object EmbeddedFixtures {")
            appendLine("    val files: Map<String, String> = mapOf(")
            entries.forEach { entry -> appendLine(entry) }
            appendLine("    )")
            appendLine("}")
        }

        val pkgDir: File = outputDir.get().asFile.resolve("co/branch/jsonlogic/fixtures")
        pkgDir.mkdirs()
        pkgDir.resolve("EmbeddedFixtures.kt").writeText(source)
    }
}

val generateFixtures = tasks.register<GenerateFixturesTask>("generateFixtures") {
    fixtureFiles.from(
        fileTree(rootProject.layout.projectDirectory.dir("fixtures")) {
            include("*.json")
        },
    )
    outputDir.set(layout.buildDirectory.dir("generated/fixtures/commonTest/kotlin"))
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }

    androidLibrary {
        namespace = "co.branch.jsonlogic"
        compileSdk = 36
        minSdk = 21

        // Gives the Android target a JVM host-test compilation so commonTest can run on
        // the Linux CI lane without a device or emulator.
        withHostTestBuilder {}.configure {
            isIncludeAndroidResources = false
        }
    }

    iosArm64()
    iosSimulatorArm64()

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        nodejs()
    }

    sourceSets {
        commonMain.dependencies {
            // Runtime artifact only: the JSON tree types are used directly, so the
            // serialization compiler plugin is not applied.
            implementation(libs.kotlinx.serialization.json)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        jvmTest.dependencies {
            // The frozen Java engine, so the JVM parity gate can diff it against this one
            // case by case. Removed together with :parity once the port is accepted.
            implementation(project(":parity"))
        }
        commonTest {
            // The output Provider registers the generated dir and its codegen task dependency together.
            kotlin.srcDir(generateFixtures.flatMap { it.outputDir })
        }
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 11
}

tasks.named<Test>("jvmTest") {
    // The parity gate tells the two engines' failures apart by the frame that raised them. Once a
    // throw site is hot, the JVM reports an implicit exception — a null dereference, an out-of-range
    // index — as a shared instance carrying no stack trace and no message, leaving nothing to tell one
    // operator's failure from another's. This keeps every throwable's own trace. Goes with :parity.
    jvmArgs("-XX:-OmitStackTraceInFastThrow")
}

// Guarantee codegen runs before every Kotlin compilation, so no compile races the generated source.
tasks.withType<KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateFixtures)
}
