import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.publish.maven.MavenPublication
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.bundling.Jar
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask
import java.io.File
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.binary.compatibility.validator)
    `maven-publish`
}

group = "co.branch"
version = "0.1.0-SNAPSHOT"

// KLib ABI validation is experimental in BCV 0.17.0, but deterministic here: iosArm64 and
// iosSimulatorArm64 main klibs compile without a full Xcode install (only linking a test
// binary needs the Xcode toolchain), and wasmJs needs nothing platform-specific. Without this,
// BCV only validates the jvm dump; it does not support this project's androidLibrary target
// either way, so klib is the only route to covering the native and wasmJs public surface.
apiValidation {
    @OptIn(kotlinx.validation.ExperimentalBCVApi::class)
    klib {
        enabled = true
    }
}

/**
 * Embeds every JSON fixture file under fixtures/ as base64 into a single generated Kotlin file,
 * so the migration's correctness-contract fixtures are readable from commonTest on every KMP
 * target, including wasmJs and iOS, which have no test-resources filesystem to read from at
 * runtime.
 *
 * Each fixture's base64 is split into chunks well under the JVM class-file 65,535-byte UTF-8
 * constant limit, so no single string literal in the generated file approaches it.
 */
abstract class GenerateFixturesTask : DefaultTask() {

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val fixtureFiles: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @OptIn(ExperimentalEncodingApi::class)
    @TaskAction
    fun generate() {
        val chunkSize = 16_000

        val jsonFiles: List<File> = fixtureFiles.files
            .filter { it.isFile && it.extension == "json" }
            .sortedBy { it.name } // deterministic output

        require(jsonFiles.isNotEmpty()) {
            "No fixture files found. Expected JSON files under fixtures/."
        }

        val entries: List<String> = jsonFiles.map { file ->
            val base64: String = Base64.encode(file.readBytes())
            val chunkLiterals: String = base64
                .chunked(chunkSize)
                .joinToString(separator = ",\n") { chunk -> "        \"$chunk\"" }

            """
            |    "${file.name}" to decodeBase64(
            |        listOf(
            |$chunkLiterals,
            |        ).joinToString(""),
            |    ),
            """.trimMargin()
        }

        val source = buildString {
            appendLine("// GENERATED by the generateFixtures Gradle task. Do not edit.")
            appendLine("package co.branch.jsonlogic.fixtures")
            appendLine()
            appendLine("import kotlin.io.encoding.Base64")
            appendLine("import kotlin.io.encoding.ExperimentalEncodingApi")
            appendLine()
            appendLine("@OptIn(ExperimentalEncodingApi::class)")
            appendLine("private fun decodeBase64(base64: String): String = Base64.decode(base64).decodeToString()")
            appendLine()
            appendLine("internal object EmbeddedFixtures {")
            appendLine("    val files: Map<String, String> = mapOf(")
            entries.forEach { entry -> appendLine(entry) }
            appendLine("    )")
            appendLine("}")
        }

        val pkgDir: File = outputDir.get().asFile.resolve("co/branch/jsonlogic/fixtures")
        pkgDir.mkdirs()
        pkgDir.resolve("EmbeddedFixtures.kt").writeText(source)
    }
}

val generateFixtures = tasks.register<GenerateFixturesTask>("generateFixtures") {
    fixtureFiles.from(
        fileTree(rootProject.layout.projectDirectory.dir("fixtures")) {
            include("*.json")
        },
    )
    outputDir.set(layout.buildDirectory.dir("generated/fixtures/commonTest/kotlin"))
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }

    androidLibrary {
        namespace = "co.branch.jsonlogic"
        compileSdk = 36
        minSdk = 21

        // Gives the Android target a JVM host-test compilation so commonTest can run on
        // the Linux CI lane without a device or emulator.
        withHostTestBuilder {}.configure {
            isIncludeAndroidResources = false
        }
    }

    iosArm64()
    iosSimulatorArm64()

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        nodejs()
    }

    sourceSets {
        commonMain.dependencies {
            // Exposed as `api`: JsonElement from this dependency appears directly in the
            // public JsonLogic.apply/parse signatures, so consumers need it on their
            // compile classpath too. The serialization compiler plugin is not applied,
            // since the JSON tree types are used directly rather than generated.
            api(libs.kotlinx.serialization.json)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        commonTest {
            // The output Provider registers the generated dir and its codegen task dependency together.
            kotlin.srcDir(generateFixtures.flatMap { it.outputDir })
        }
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 11
}

// Guarantee codegen runs before every Kotlin compilation, so no compile races the generated source.
tasks.withType<KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateFixtures)
}

// Embeds the repository's MIT license text (upstream jamsesso/json-logic-java's copyright
// notice) into the jvm jar's META-INF, its conventional slot on the JVM classpath.
//
// The android target's AAR has no equivalent slot: its BundleAar task extends Gradle's plain
// Zip, not Jar, so it exposes no metaInf CopySpec (or documented alternative) to hook into.
// Likewise, klib archives (iosArm64/iosSimulatorArm64/wasmJs) have no license-embedding
// convention in the Kotlin/Native ecosystem. Those artifacts carry the license only through
// each publication's POM <licenses> block and the repository's top-level LICENSE file.
tasks.named<Jar>("jvmJar") {
    metaInf {
        from(layout.projectDirectory.file("LICENSE"))
    }
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/BranchIntl/json-logic-kmp")
            credentials {
                username = providers.environmentVariable("GITHUB_ACTOR").orNull
                password = providers.environmentVariable("GITHUB_TOKEN").orNull
            }
        }
    }

    publications.withType<MavenPublication>().configureEach {
        pom {
            name = "json-logic-kmp"
            description = "Kotlin Multiplatform port of jamsesso/json-logic-java"
            url = "https://github.com/BranchIntl/json-logic-kmp"
            inceptionYear = "2026"
            licenses {
                license {
                    name = "MIT License"
                    url = "https://github.com/BranchIntl/json-logic-kmp/blob/main/LICENSE"
                    distribution = "repo"
                }
            }
            developers {
                developer {
                    id = "BranchIntl"
                    name = "Branch International"
                    url = "https://github.com/BranchIntl"
                }
            }
            scm {
                url = "https://github.com/BranchIntl/json-logic-kmp"
                connection = "scm:git:https://github.com/BranchIntl/json-logic-kmp.git"
                developerConnection = "scm:git:ssh://git@github.com/BranchIntl/json-logic-kmp.git"
            }
        }
    }
}
